services:
  node-red:
    build: .
    container_name: node-red
    environment:
      VIRTUAL_HOST: ${NODE_RED_HOST}
      VIRTUAL_PORT: 1880
      LETSENCRYPT_HOST: ${NODE_RED_HOST}
      TZ: America/Bogota
    volumes:
      - "./:/data"
      - "./settings_dcevedo.js:/data/settings.js"
    networks:
      - nginx-proxy
networks:
  nginx-proxy:
    external: true

