services:
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=America/Bogota
    ports:
      - "1880:1880"
    volumes:
      - "../package.json:/data/package.json" 
      - "../package-lock.json:/data/package-lock.json"
      - "../flows.json:/data/flows.json"
      - "../flows_cred.json:/data/flows_cred.json"
      - "../settings_dcevedo.js:/data/settings.js"
